src/Entity/Messages.php
<?php

namespace App\Entity;

use App\Repository\MessagesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MessagesRepository::class)]
class Messages
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $message = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $postedAt = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\ManyToOne(inversedBy: 'messages')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $Auteur = null;

    #[ORM\OneToMany(mappedBy: 'Tweet', targetEntity: Commentaires::class)]
    private Collection $commentaires;

    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'messages')]
    private Collection $categories;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
        $this->postedAt = new \DateTimeImmutable("now");
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getmessage(): ?string
    {
        return $this->message;
    }

    public function setmessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getPostedAt(): ?\DateTimeImmutable
    {
        return $this->postedAt;
    }

    public function setPostedAt(\DateTimeImmutable $postedAt): self
    {
        $this->postedAt = $postedAt;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getAuteur(): ?User
    {
        return $this->Auteur;
    }

    public function setAuteur(?User $Auteur): self
    {
        $this->Auteur = $Auteur;

        return $this;
    }

    /**
     * @return Collection<int, Commentaires>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaires $commentaire): static
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
        }

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): static
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
        }

        return $this;
    }

    public function removeCategory(Category $category): static
    {
        $this->categories->removeElement($category);

        return $this;
    }
}

templates/base.html.twig
{% set route_name = app.request.attributes.get('_route') %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <link rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
    <title>
        WebDev & confessions - {% block title %}{% endblock %}
    </title>
    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
        <link
                rel="stylesheet"
                href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
                integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
                crossorigin="anonymous"
        />

    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}
    {% endblock %}
</head>
<body>
<div class="container">
    <div class="profile-wrapper">
        {% include '_commun/_profile.html.twig' %}
        <div class="profile-section-main">
            {% include '_commun/_tabs.html.twig' %}
            {% block body %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

templates/index.html.twig
{% extends "base.html.twig" %}

{% block title %}Accueil{% endblock %}

{% block body %}
        <div class="tab-content profile-tabs-content">
            <div class="tab-pane active" id="profile-overview" role="tabpanel">
                <div class="post-editor">
                    {{ form_start(form) }}
                    {{ form_widget(form.message) }}
                    <div class="d-flex mb-2">
                        {{ form_widget(form.image) }}
                    </div>
                    <div class="d-flex">
                        <button class="btn btn-success px-4 py-1">Se confesser</button>
                    </div>
                    {{ form_end(form) }}
                    {% for type, messages in app.session.flashbag.all() %}
                        {% for message in messages %}
                            {% if type == 'danger' %}
                                <div class="alert alert-danger">
                                    {{ message }}
                                </div>
                            {% elseif type == 'success' %}
                                <div class="alert alert-success">
                                    {{ message }}
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% endfor %}

                </div>
                {% for confession in messages %}
                    <div class="stream-posts">
                        <div class="stream-post">
                            <div class="sp-author">
                                {% if confession.auteur.avatar is not null %}
                                    <a href="#" class="sp-author-avatar"><img
                                                src="{{ asset('uploads/images/' ~ confession.auteur.avatar) }}"
                                                alt=""></a>
                                {% else %}
                                    <a href="#" class="sp-author-avatar"><img
                                                src="https://static.vecteezy.com/system/resources/previews/014/033/545/original/geek-emoticon-yellow-color-free-png.png"
                                                alt=""></a>
                                {% endif %}
                                <h6 class="sp-author-name"><a
                                            href="#">{{ confession.auteur.firstname }} {{ confession.auteur.lastname }}</a>
                                </h6></div>
                            <div class="sp-content">
                                <div class="sp-info">
                                    @{{ confession.auteur.username }} posté
                                    le {{ confession.postedAt|date('d/m/Y à H:i', "Europe/Paris") }}</div>
                                <p class="sp-paragraph mb-0">
                                    {{ confession.message|raw }}
                                </p>
                                {% if confession.image is not null %}
                                    <img src="{{ asset('uploads/images/' ~ confession.image) }}" alt=""
                                         class="img-fluid">
                                {% endif %}
                            </div>
                            <div class="sp-footer">
                                <div class="sp-footer-actions">
                                    <p class="sp-footer-action">
                                        <i class="fa fa-heart"></i> 0
                                        <a href="{{ path('messages_show', {'id': confession.id}) }}"
                                           class="sp-footer-action"><i
                                                    class="fa fa-comment"></i> {{ confession.commentaires|length }}
                                        </a>
                                        {% if confession.auteur == app.user or is_granted("ROLE_ADMIN") %}
                                            {{ include('messages/_delete.html.twig') }}
                                        {% endif %}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
{% endblock %}